### POST request: create new recipe
POST http://localhost:8080/recipe/create
Content-Type: application/json

{
  "name": "Kopfsalat",
  "ingredients": [
    {
      "name": "Kopfsalat",
      "amount": 1,
      "unit": "St"
    },
    {
      "name": "Wasser",
      "amount": 2,
      "unit": "EL"
    },
    {
      "name": "Rapsöl",
      "amount": 1,
      "unit": "EL"
    },
    {
      "name": "Zitrone",
      "amount": 1,
      "unit": "St"
    },
    {
      "name": "Schalotte",
      "amount": 1,
      "unit": "St"
    },
    {
      "name": "Zucker",
      "amount": 2,
      "unit": "TL"
    },
    {
      "name": "Salz"
    },
    {
      "name": "Pfeffer"
    }
  ],
  "method": ["Salat waschen und trocken schütteln (am besten mit der Salatschleuder). Den Strunk entfernen und ihn in mundgerechte Stücke teilen.",
    "Schalotte schälen und sehr fein würfeln und Zitrone auspressen. Den Zitronensaft mit Rapsöl, Wasser, Zucker, Salz und den Schalottenwürfeln verrühren.",
    "Das Dressing unter den Salat heben."],
  "portions": 4,
  "mealType": "Salat",
  "diet": "Vegan"
}

### POST request: create new recipe
POST http://localhost:8080/recipe/create
Content-Type: application/json

{
    "name": "Tomate Mozzarella",
    "ingredients": [
    {
    "name": "Tomaten",
    "amount": 250,
    "unit": "g"
    },
    {
    "name": "Mozzarella",
    "amount": 1,
    "unit": "St"
    },
    {
    "name": "Olivenöl",
    "amount": 1,
    "unit": "EL"
    },
    {
    "name": "Balsamico",
    "amount": 1,
    "unit": "EL"
    },
    {
    "name": "getrockneter Oregano"
    },
    {
    "name": "Knoblauchpulver"
    },
    {
    "name": "Salz"
    },
    {
    "name": "Pfeffer"
    }
    ],
    "method": ["Tomaten waschen und in Scheiben schneiden. Mozzarella in ähnlich große Scheiben schneiden wie die Tomaten.",
    "Tomatenscheiben auf einem Teller verteilen und die Mozzarellascheiben darauf verteilen.",
    "Öl und Balsamico darüber verteilen und mit Oregano, Knoblauchpulver, Salz und Pfeffer würzen."],
    "portions": 1,
    "mealType": "Salat",
    "diet": "Vegetarisch"
}

### POST request: create new recipe without the non-optional fields "ingredients" and "method"
POST http://localhost:8080/recipe/create
Content-Type: application/json

{
  "name": "Lasagne",
  "portions": 4,
  "utensils": ["Auflaufform"],
  "mealType": "Hauptmahlzeit",
  "primaryCarb": "Nudeln"
}

### GET request: show all saved recipes
GET http://localhost:8080/recipes

### GET request: show recipe with ID 1
GET http://localhost:8080/recipe/1

### GET request: show recipe with ID 5 (not existent)
GET http://localhost:8080/recipe/5

### DELETE request: delete recipe with ID 1
DELETE http://localhost:8080/recipe/delete/1

### PUT request: replace recipe with ID 2 with updated version
PUT http://localhost:8080/recipe/update/2
Content-Type: application/json

{
    "name": "Tomate Mozzarella",
    "ingredients": [
    {
    "name": "Tomaten",
    "amount": 250,
    "unit": "g"
    },
    {
    "name": "Mozzarella",
    "amount": 1,
    "unit": "St"
    },
    {
    "name": "Olivenöl",
    "amount": 1,
    "unit": "EL"
    },
    {
    "name": "Balsamico",
    "amount": 1,
    "unit": "EL"
    },
    {
    "name": "Basilikum"
    },
    {
    "name": "Knoblauch",
    "amount": 1,
    "unit": "Zehe"
    },
    {
      "name": "Zwiebel",
      "amount": 1,
      "unit": "St",
      "additional": "klein"
    },
    {
    "name": "Salz"
    },
    {
    "name": "Pfeffer"
    }
    ],
    "method": ["Tomaten waschen und in Scheiben schneiden. Mozzarella in ähnlich große Scheiben schneiden wie die Tomaten. Zwiebel und Knoblauch schälen, Knoblauch fein Würfeln und Zwiebel in feine Ringe schneiden,",
    "Tomatenscheiben auf einem Teller legen und die Mozzarellascheiben darauf und danach Knoblauch und Zwiebel darüber verteilen.",
    "Öl und Balsamico darübergießen und mit Salz und Pfeffer würzen. Mit Basilikum dekorieren."],
    "portions": 1,
    "mealType": "Salat",
    "diet": "Vegetarisch"
}